### ISSUE TITLE
Mac computer at my desk

### ISSUE THREAD

**Issue by GiriKrish** [kmcgregor123456/CVNRimagingCore#15]
Hi Keith,

The Mac computer at my desk has the same issue as the one in imaging lab. It keeps flashing pink and purple pixels. Is this a graphic card issue ?

Thanks,
Giri.

**Comment by kmcgregor123456** [comment]
I will fix. It's a video card driver issue. It can be fixed by upgrading to Mac OS 10.13 (high sierra).  machine will have to be down for about 2 hours to complete.


================
Keith M. McGregor, PhD
VA RR&D Atlanta CVNR
Emory University, Department of Neurology
352.359.8084
www.varrd.emory.edu<http://www.varrd.emory.edu>

________________________________

**Comment by GiriKrish** [comment]
Thanks, Keith. Monday, Wednesday and Thursday are my VA days. It would be good if we can plan to do the upgrade on Tue or Fri.

Thanks,
Giri.

**Comment by kmcgregor123456** [comment]
Ill do it today. Requires a reboot

Best,

-------------------
Keith McGregor, PhD
Atlanta VA CVNR
Emory University
www.varrd.emory.edu<http://ww.varrd.emory.edu>


On Apr 27, 2018, at 10:55, GiriKrish <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks, Keith. Monday, Wednesday and Thursday are my VA days. It would be good if we can plan to do the upgrade on Tue or Fri.

Thanks,
Giri.

**Comment by GiriKrish** [comment]
Hi Keith,

Thanks for taking care of my Mac computer on Friday. So far it seems like it’s working fine…thanks again. ☺

Best,
Giri.

**Comment by kmcgregor123456** [comment]
no worries
