### ISSUE TITLE
FNIRT on qball1 does  not work

### ISSUE THREAD

**Issue by GiriKrish** [kmcgregor123456/CVNRimagingCore#44]
When i try to run FNIRT on qball1, it keeps saying that config file cannot be found. I tried providing full path to the config file...fnirt command does not take full path for the config file. however, when I logged in to lens, fnirt runs fine. I guess qball1 needs fsl upgrade or path setup checked.
Thanks,
Giri.

**Comment by kmcgregor123456** [comment]
Looking into it now.


================
Keith M. McGregor, PhD
VA RR&D Atlanta CVNR
Emory University, Department of Neurology
352.359.8084
www.varrd.emory.edu<http://www.varrd.emory.edu>

________________________________

**Comment by kmcgregor123456** [comment]
For some reason, your bashrc script does is calling the /usr/local/X11/bin directory.  Do you want me to replace your bashrc with an updated one?

**Comment by GiriKrish** [comment]
Sure, if that helps. Thanks 😀


-------- Original message --------

**Comment by kmcgregor123456** [comment]
Cool. Bashrc configurations can be a very touchy thing. Sometimes shell users like everything just exactly so , especially so in bash.

I think it should be fixed by tomorrow afternoon.

Best,

-------------------
Keith McGregor, PhD
Atlanta VA CVNR
Emory University
www.varrd.emory.edu<http://ww.varrd.emory.edu>


On Jul 17, 2018, at 22:10, GiriKrish <notifications@github.com<mailto:notifications@github.com>> wrote:

Sure, if that helps. Thanks 😀


-------- Original message --------
