### ISSUE TITLE
QCA R packages

### ISSUE THREAD

**Issue by MRphysics4life** [kmcgregor123456/CVNRimagingCore#63]
Could we please install the following R packages: CNA, QCApro
This will allow us to perform QCA analysis on our data.
Thanks!
-LCK

**Comment by kmcgregor123456** [comment]
I installed the software. 

Are we doing QCA? QCA is usually used for social sciences and health outcomes research. It's probably not going to be useful for imaging research since it is wholly dependent on OR gating (i.e. - booleans). QCA is kind of controversial even in the social sciences because it requires a set threshold for binarizing outcomes within each variable of interest.
